# The logging configuration. On a real server this will be a file url. e.g. file://{{ mujina_dir }}/logback.xml
logging:
  config: classpath:logback.xml

server:
  # The port to where this Spring Boot application listens to. e.g. http://localhost:{{ springapp_tcpport }}
  port: 18090
  # The context path of the server. You can skip this value in the overriding application.yml on the classpath
  contextPath:
  session:
    # 8 hours before we time-out
    timeout: 28800
    cookie:
      secure: false

# Identity Provider
idp:
  entity_id: http://rakrak-dev02
  # base url
  base_url: http://localhost:18090
  # Private key used to sign the SAML response
  private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQD5++484KNnB37uZnU1SN8F4SffnP/Hdc44GtMT3p5+lnhvb22C9zJftugBBHz9KeHcB48nxrLvXK0SJJYxlMyxUUzNpNq78jT2skeYM4j9xOlLjLVEkqGvfPHVrJZ+AKlBJUW2E4KswMPkkhavMrCXeN5p5DX2+DcCxpu97z7G4+p6P8lvkHUi3ADqV1hwXm+BdVn3C+6g/MQamb5rVuk0RMqJVA0Lz/JFc++KnIXi9vi9Upc7TSAYwwW45H9ULYft50mxHpZeS9kC56a6sBsh5wqS+/yfUgxRbOO46c5Oy1m757ewMUyNT9m2FqtLNrxMiTV1nEQgYFyaprGZ4wx9AgMBAAECggEBAJTUgvBHpcEvW0jAQ0PoEK/FbyHYrQepgY8xmT2ZKq+fEjD2HDL+zUTi9pm0fF2VU9zVu0spJ1sOyBOnKKx4NK3VA27jmT6QYywE1E8vT34Wf/b03O7ohc6fCrP2PtrhteMNN8XBM+l6EqbAuzSvbyefVHui3OYevVGvwQWBrNRnq/J7y2L6RplgwDX/DfJzXCohZHv/ueVdQOb6hejqE3MITq/cku/rVFAMT+t8Uudw7ej5IhpY+2rbIB2ovURYFgRUTjuP6p2luXRPqzuDlowLwRfqmDpH16mqkdfORA0Wkvkzsk40AJTjFgD//cUmluLyd4966UjZ2XIARRD+PVkCgYEA/4YG1V0xNEOBn1cZKMWM3Qq13J50A6ER/m4yXwP6WBPjaYI0HZs0eRtAHnh9sDncfAw7/I+BOOFSrnwXkEiNBEiTzaqF8Qc02OvSMBVWYU5wdHm4VKJcJzcgtGP4XFLtuDY5yN+6isnYZ6zud3ET6TtDaP47bMXfJ6h0r3/CvCMCgYEA+nNCex6u0NZ8mz364hDtN2mg9qa1TJT6JkpRy0WBrIgIqXle+2QS7DX4CEpEve/wG1bTytHUms6uYDvxJRNIDjMpSwdNy8PD51dwy+6egwRoKFjh6+cSg8QOq+XdCo8vGyBpUgS22nrWcaeYCZ4WM2MX7vb8804mOqECrsf/zt8CgYEA2fIchAKwBE8MEbe9quwNQUBwbBPvCmVpLqYZare+4T9delHnV9VZBW872oGVWymPKXNZ+wsAAl8WIeOQSa3IMf4hq4umITavWdKS/hZFDkxUWNS1Z+LwTTaVO6gFX+IQB06hLPe/ab/OSGfVIqWdgRLeZYBreVSxCWeC12pW1BcCgYEA31YtMLG53s2GLMHmmfXSNBnjyk/7WKF5OPAJZKVE7+AXKVnsU214Wl/+IRZpmp7+lMKm9zSKzMoGQhbyAcfh95ez+Q44V77pUcFt+s19WQRzBZfNT5qtrgcFtlCy/pmUvjH2+YbusIHd/VgggmMRFR4G17g09Zr5CEtQoyAChC0CgYAi6Kv2PTdNWQgqpgPNNwWaCgrOZuwnjnsdffFrgH7GYg70dfJx+B9NvNVkFpHUSVS9UE8Wt3cdj8UQ3CFZY3hXEuZN4iMcGK9L4QDolvsNcJirn+gaFhE6hDgMqhIq8Xn9nPyIx8aRY02jhU8VXlGYoyPIOq/B/q49qCRXoM4hxA== 
 # Public certificate to verify the signature of the SAML response
  certificate: MIIDFzCCAf+gAwIBAgIJAPy9t3uP04BBMA0GCSqGSIb3DQEBCwUAMCIxIDAeBgNVBAoMF09yZ2FuaXphdGlvbiwgQ049TXVqaW5hMB4XDTE3MDYwNjA5MDIyNVoXDTI3MDYwNjA5MDIyNVowIjEgMB4GA1UECgwXT3JnYW5pemF0aW9uLCBDTj1NdWppbmEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQD5++484KNnB37uZnU1SN8F4SffnP/Hdc44GtMT3p5+lnhvb22C9zJftugBBHz9KeHcB48nxrLvXK0SJJYxlMyxUUzNpNq78jT2skeYM4j9xOlLjLVEkqGvfPHVrJZ+AKlBJUW2E4KswMPkkhavMrCXeN5p5DX2+DcCxpu97z7G4+p6P8lvkHUi3ADqV1hwXm+BdVn3C+6g/MQamb5rVuk0RMqJVA0Lz/JFc++KnIXi9vi9Upc7TSAYwwW45H9ULYft50mxHpZeS9kC56a6sBsh5wqS+/yfUgxRbOO46c5Oy1m757ewMUyNT9m2FqtLNrxMiTV1nEQgYFyaprGZ4wx9AgMBAAGjUDBOMB0GA1UdDgQWBBRwYXMl9xnHrKbBZHPkON3nEYiwoDAfBgNVHSMEGDAWgBRwYXMl9xnHrKbBZHPkON3nEYiwoDAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAkE5+QDOod8uUB/cZ+v/rvV9ctGY+mUK7k1PTVcf7yBV2TLU5WZ9mfhjLihYWHnNb9qPM+1WcvnYeTCbVe/IuUKoG9F19JtHi2EWVdvIQwYxEIjio5vWmtUJTeOC2BIJm7sokceezeFmhNwSjJ/KQV7vSg+WK9qz4/IPvBS07T7ea7uA6kS7NmCg/NzeS7CecgzYNz1C8jUSTj6zKq//zi2nEjdTMc5XKTkeO43pmJ9nNP8nIQJKCdplvH61E1qk1YwBOFllO38XwtCS/SbRzTDFFhhUq+gmPTn2b4b1aAPMqS0DdxWIsAVbxNwgH/Z7j9WGWvMY7AqkPo/Tor6kl4
  # Passphrase of the keystore
  passphrase: secret
  # The number of seconds before a lower time bound, or after an upper time bound, to consider still acceptable
  clock_skew: 36000 
  # Number of seconds after a message issue instant after which the message is considered expired
  expires: 36000
  # Authentication method ALL for every username / password combination and USER for the configured users
  auth_method: USER 
  # Are endpoints compared. If so then pay notice to the base_url when behind a load balancer
  compare_endpoints: false

spring:
  mvc:
    favicon:
      enabled: false
  velocity:
    check-template-location: False

# We disable all endpoints except health for the load-balancer and info for git information.
endpoints:
  enabled: false
  jmx:
    enabled: false
  health:
    enabled: true
  info:
    enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
